### ISSUE TITLE
Missing some functions from User32.dll

### ISSUE THREAD

**Issue by Trapov** [prasannavl/WinApi#15]
Well, first of all, great project, loving it. Is there by any chance any **Clipboard implementation** incoming in the future, such as:

- SetClipboardViewer
- ChangeClipboardChain

and e.t.c?

**Comment by prasannavl** [comment]
Please contribute :) PRs are welcome.

They should be easy to do. If you don't want to look at the C header files, sites like Pinvoke.net and MSDN should do it.
