### ISSUE TITLE
HWND wrapper

### ISSUE THREAD

**Issue by midiway** [prasannavl/WinApi#3]
I just need a simple HWND wrapper class, to call methods like SetWindowPos, ModifyStyle, GetWindowPlacement, no need to create windows, or any kind of WinProc wrapper.

Do you have a complete one in your lib?
Or can you recommend another lib?

**Comment by prasannavl** [comment]
The `NativeWindow` class that's in the `WinApi.Windows` namespace is designed precisely for this purpose. I've written about its basics here: https://www.prasannavl.com/2016/10/introducing-winapi-basics.

Should cover exactly what you need. 

Note though, however it may not be complete. I've only added wrappers for only certain common items. Feel free to add a method back in into the class and contribute back if you find something missing :)

**Comment by midiway** [comment]
Ok, gonna check, that yet it is very incomplete
Right now I am resorting to https://github.com/AArnott/pinvoke

**Comment by prasannavl** [comment]
No problem! That's what I myself mix this with. :) 
My initial focus was only on the common GUI usage set. Hopefully, I'll try add more soon.
