### ISSUE TITLE
GetWindowThreadProcessId wrong results

### ISSUE THREAD

**Issue by deadlocklogic** [prasannavl/WinApi#59]
I am trying this snippet with wrong values:
```C#
protected static IntPtr FindWindowByProcessId(int pid)
{
    IntPtr HWND = IntPtr.Zero;
    WinApi.User32.User32Methods.EnumWindows(new WinApi.User32.EnumWindowsProc((hWnd, lParam) =>
    {
        uint currentPID = WinApi.User32.User32Methods.GetWindowThreadProcessId(hWnd, IntPtr.Zero);
        if (currentPID == ((uint)pid))
        {
            if (WinApi.User32.User32Methods.IsWindowVisible(hWnd))
            {
                HWND = hWnd;
                return false;
            }
        }

        return true;
    }), IntPtr.Zero);

    return HWND;
}
```
Any thoughts?

**Comment by zodiacon** [comment]
GetWindowThreadProcessId returns the thread ID directly - not the process ID

**Comment by deadlocklogic** [comment]
But using handwritten bindings is giving correct results:
```C#
private static IntPtr FindWindowByProcessId1(int pid)
{
    IntPtr HWND = IntPtr.Zero;
    ManualWinAPI.EnumWindows(new ManualWinAPI.EnumWindowsProc((tophandle, topparamhandle) =>
    {
        _ = ManualWinAPI.GetWindowThreadProcessId(tophandle, out int cur_pid);
        if (cur_pid == pid)
        {
            if (ManualWinAPI.IsWindowVisible(tophandle))
            {
                HWND = tophandle;
                return false;
            }
        }

        return true;
    }), IntPtr.Zero);

    return HWND;
}
```

**Comment by zodiacon** [comment]
It's not the same code - you're getting the PID correctly in this case - notice the "out int cur_pid". The original code compares the thread ID.

**Comment by deadlocklogic** [comment]
How should I correct the first code then? The method doesn't support raw types as `out` in the API.

**Comment by zodiacon** [comment]
You could use raw pointers in an unsafe context. I'm not the owner of the API, it should have an overload that accepts an "out uint pid".

**Comment by deadlocklogic** [comment]
> You could use raw pointers in an unsafe context. I'm not the owner of the API, it should have an overload that accepts an "out uint pid".

Unfortunately no overloads there and I don't think passing unsafe pointers is possible.
